Repository Utkarsh-username/Clippy-PFP-Generator, pull requests merged in 2025-10, with the labels that each got.

#7 feat: updated issue template and pr template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest, hacktoberfest-accepted

#9 removed-noisy-BGs
  assets/bg/bg_1.png
  assets/bg/bg_10.png
  assets/bg/bg_11.png
  assets/bg/bg_12.png
  assets/bg/bg_14.png
  assets/bg/bg_15.png
  assets/bg/bg_19.png
  assets/bg/bg_20.png
  assets/bg/bg_21.png
  assets/bg/bg_22.png
  assets/bg/bg_23.png
  manifest.json
Labels: hacktoberfest

#10 Fix/update readme
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#12 feat: add support for solid color and gradient backgrounds in builder…
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
